import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTimestampsAndSoftDelete1774297640209 implements MigrationInterface {
    name = 'AddTimestampsAndSoftDelete1774297640209'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "FK_eb8559946673fe848e1a2d42602"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "FK_b59ebeb74c39385a22914bac017"`);
        await queryRunner.query(`ALTER TABLE "machines" DROP CONSTRAINT "FK_292287f1c44bff51dc5b4e2ee4f"`);
        await queryRunner.query(`ALTER TABLE "machines" DROP CONSTRAINT "FK_8966ebe117dc2bc64dd95af9cda"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "fk_tickets_resolved_by_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "fk_tickets_assigned_to_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "fk_tickets_reported_by_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "fk_tickets_machine_id"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "fk_tickets_tenant_id"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_ticket"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_work_order"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_visit"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "fk_attachments_tenant"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_c2e6755ee65c580615296677e16"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_194460786aece8cab095bec7a75"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_8575b345fcc2bc2fc2161295cba"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "fk_work_orders_visit_id"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "fk_work_orders_assigned_user_id"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "fk_work_orders_machine_id"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "fk_work_orders_tenant_id"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_sync_queue_user_id"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_sync_queue_tenant_id"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_d6c187cbf5d2268060086127829"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec74afdbe891f317df5a23c137"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tickets_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attachments_tenant_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_work_orders_tenant_id"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "hardware_model"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "operation_type"`);
        await queryRunner.query(`DROP TYPE "public"."sync_queue_operation_type_enum"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "last_error"`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."sync_queue_operationtype_enum" AS ENUM('visit_check_in', 'visit_check_out', 'work_order_delivery', 'ticket_report', 'ticket_update', 'attachment_upload')`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "operationType" "public"."sync_queue_operationtype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "max_retries" integer NOT NULL DEFAULT '3'`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "error_message" text`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "error_stack" text`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "next_retry_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "slug" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'SUPPORT', 'VENDOR', 'RETAILER', 'TECHNICIAN', 'DRIVER')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."fcm_tokens" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "UQ_eb8559946673fe848e1a2d42602" UNIQUE ("machine_id")`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "uid"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "uid" character varying(14) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b" UNIQUE ("uid")`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "machine_serial_id"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "machine_serial_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "tenant_id_obfuscated"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "tenant_id_obfuscated" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "integrity_checksum"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "integrity_checksum" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "machines" DROP COLUMN "model"`);
        await queryRunner.query(`ALTER TABLE "machines" ADD "model" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "machines" DROP COLUMN "serial_number"`);
        await queryRunner.query(`ALTER TABLE "machines" ADD "serial_number" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "machines" ADD CONSTRAINT "UQ_c7c3a3353238c4e71535a30ddd3" UNIQUE ("serial_number")`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "location_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "location_lat" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "location_lng" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "can_use_manual_entry" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attachments" ALTER COLUMN "type" SET DEFAULT 'foto'`);
        await queryRunner.query(`ALTER TABLE "attachments" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attachments" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "visits" DROP COLUMN "check_in_nfc_uid"`);
        await queryRunner.query(`ALTER TABLE "visits" ADD "check_in_nfc_uid" character varying(14) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visits" DROP COLUMN "check_out_nfc_uid"`);
        await queryRunner.query(`ALTER TABLE "visits" ADD "check_out_nfc_uid" character varying(14)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_in_gps_lat" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_in_gps_lng" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_out_gps_lat" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_out_gps_lng" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "nfc_validated" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "expected_location_lng" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "actual_location_lng" TYPE numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "user_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."sync_queue_status_enum" RENAME TO "sync_queue_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sync_queue_status_enum" AS ENUM('pendiente', 'sincronizado', 'fallido', 'revision_manual')`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "status" TYPE "public"."sync_queue_status_enum" USING "status"::"text"::"public"."sync_queue_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "status" SET DEFAULT 'pendiente'`);
        await queryRunner.query(`DROP TYPE "public"."sync_queue_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "entity_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "entity_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "FK_eb8559946673fe848e1a2d42602" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "FK_b59ebeb74c39385a22914bac017" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "machines" ADD CONSTRAINT "FK_8966ebe117dc2bc64dd95af9cda" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "machines" ADD CONSTRAINT "FK_292287f1c44bff51dc5b4e2ee4f" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_d4beb915a8f7487afcb2d073c01" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_9ad7b44d2ebc86a477684e98f11" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_b7727d55e780e042d7a16565916" FOREIGN KEY ("reported_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_b564a18159530b5a56aeac33d1a" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ce5e516016201cf1b8cb005ee42" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_7058f2082c7a4ddc189ad7c9a86" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_70a38fc450d3b433c86b67e69d6" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_f2ece73b5779f73248c00b0fa88" FOREIGN KEY ("visit_id") REFERENCES "visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_04fb88c0c47ca92f20d1b5f5fca" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_73d871f247ffebda5dc3f0df8a4" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_8575b345fcc2bc2fc2161295cba" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_194460786aece8cab095bec7a75" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_c2e6755ee65c580615296677e16" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_0059be3d968bef25dcf779f043e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_cb53584b8b20af62e8a78ce8a6f" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_49a14f52a9311036c7552184784" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_86b813712f13125792a274815be" FOREIGN KEY ("visit_id") REFERENCES "visits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_d6c187cbf5d2268060086127829" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_1605c43d06cf9c9c3059eaa4e62" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_1605c43d06cf9c9c3059eaa4e62"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_d6c187cbf5d2268060086127829"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_86b813712f13125792a274815be"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_49a14f52a9311036c7552184784"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_cb53584b8b20af62e8a78ce8a6f"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_0059be3d968bef25dcf779f043e"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_c2e6755ee65c580615296677e16"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_194460786aece8cab095bec7a75"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_8575b345fcc2bc2fc2161295cba"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_73d871f247ffebda5dc3f0df8a4"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_04fb88c0c47ca92f20d1b5f5fca"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_f2ece73b5779f73248c00b0fa88"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_70a38fc450d3b433c86b67e69d6"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_7058f2082c7a4ddc189ad7c9a86"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ce5e516016201cf1b8cb005ee42"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_b564a18159530b5a56aeac33d1a"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_b7727d55e780e042d7a16565916"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_9ad7b44d2ebc86a477684e98f11"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_d4beb915a8f7487afcb2d073c01"`);
        await queryRunner.query(`ALTER TABLE "machines" DROP CONSTRAINT "FK_292287f1c44bff51dc5b4e2ee4f"`);
        await queryRunner.query(`ALTER TABLE "machines" DROP CONSTRAINT "FK_8966ebe117dc2bc64dd95af9cda"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "FK_b59ebeb74c39385a22914bac017"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "FK_eb8559946673fe848e1a2d42602"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "entity_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "entity_id" uuid`);
        await queryRunner.query(`CREATE TYPE "public"."sync_queue_status_enum_old" AS ENUM('PENDIENTE', 'SINCRONIZADO', 'FALLIDO', 'REVISION_MANUAL')`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "status" TYPE "public"."sync_queue_status_enum_old" USING "status"::"text"::"public"."sync_queue_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "status" SET DEFAULT 'PENDIENTE'`);
        await queryRunner.query(`DROP TYPE "public"."sync_queue_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."sync_queue_status_enum_old" RENAME TO "sync_queue_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ALTER COLUMN "user_id" SET DEFAULT '00000000-0000-0000-0000-000000000000'`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "actual_location_lng" TYPE numeric(11,7)`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "expected_location_lng" TYPE numeric(11,7)`);
        await queryRunner.query(`ALTER TABLE "work_orders" ALTER COLUMN "nfc_validated" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_out_gps_lng" TYPE numeric(11,8)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_out_gps_lat" TYPE numeric(10,8)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_in_gps_lng" TYPE numeric(11,8)`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "check_in_gps_lat" TYPE numeric(10,8)`);
        await queryRunner.query(`ALTER TABLE "visits" DROP COLUMN "check_out_nfc_uid"`);
        await queryRunner.query(`ALTER TABLE "visits" ADD "check_out_nfc_uid" character varying`);
        await queryRunner.query(`ALTER TABLE "visits" DROP COLUMN "check_in_nfc_uid"`);
        await queryRunner.query(`ALTER TABLE "visits" ADD "check_in_nfc_uid" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attachments" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "attachments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "attachments" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "can_use_manual_entry" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "location_lng" TYPE numeric(11,8)`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "location_lat" TYPE numeric(10,8)`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "location_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "machines" DROP CONSTRAINT "UQ_c7c3a3353238c4e71535a30ddd3"`);
        await queryRunner.query(`ALTER TABLE "machines" DROP COLUMN "serial_number"`);
        await queryRunner.query(`ALTER TABLE "machines" ADD "serial_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "machines" DROP COLUMN "model"`);
        await queryRunner.query(`ALTER TABLE "machines" ADD "model" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "integrity_checksum"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "integrity_checksum" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "tenant_id_obfuscated"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "tenant_id_obfuscated" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "machine_serial_id"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "machine_serial_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "uid"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "uid" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b" UNIQUE ("uid")`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "UQ_eb8559946673fe848e1a2d42602"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."fcm_tokens" IS 'JSON array of FCM token strings'`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('ADMIN', 'SUPPORT', 'VENDOR', 'RETAILER', 'TECHNICIAN', 'DRIVER')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "next_retry_at"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "error_stack"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "error_message"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "max_retries"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP COLUMN "operationType"`);
        await queryRunner.query(`DROP TYPE "public"."sync_queue_operationtype_enum"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "last_error" text`);
        await queryRunner.query(`CREATE TYPE "public"."sync_queue_operation_type_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE')`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD "operation_type" "public"."sync_queue_operation_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "hardware_model" character varying NOT NULL DEFAULT 'NTAG215'`);
        await queryRunner.query(`CREATE INDEX "idx_work_orders_tenant_id" ON "work_orders" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_attachments_tenant_id" ON "attachments" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tickets_tenant_id" ON "tickets" ("tenant_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ec74afdbe891f317df5a23c137" ON "machines" ("tenant_id", "serial_number") `);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_d6c187cbf5d2268060086127829" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_sync_queue_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_sync_queue_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "fk_work_orders_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "fk_work_orders_machine_id" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "fk_work_orders_assigned_user_id" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "fk_work_orders_visit_id" FOREIGN KEY ("visit_id") REFERENCES "visits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_8575b345fcc2bc2fc2161295cba" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_194460786aece8cab095bec7a75" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_c2e6755ee65c580615296677e16" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_uploaded_by" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_visit" FOREIGN KEY ("visit_id") REFERENCES "visits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_work_order" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_ticket" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_tenant_id" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_machine_id" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_reported_by_id" FOREIGN KEY ("reported_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_assigned_to_id" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "fk_tickets_resolved_by_id" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "machines" ADD CONSTRAINT "FK_8966ebe117dc2bc64dd95af9cda" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "machines" ADD CONSTRAINT "FK_292287f1c44bff51dc5b4e2ee4f" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "FK_b59ebeb74c39385a22914bac017" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "FK_eb8559946673fe848e1a2d42602" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
